lots/urls.py
#from django.conf.urls import patterns, include, url
#ASKoiman - refactoring for Django 1.11.1
from django.conf.urls import include, url
import lots_admin
import lots_client
from lots_admin import views
from lots_client import views
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    url(r'^$', lots_client.views.home, name='home'),
    url(r'^status/$', lots_client.views.status, name='status'),
    url(r'^apply/$',  lots_client.views.apply, name='apply'),
    url(r'^apply-confirm/(?P<tracking_id>\S+)/$', lots_client.views.apply_confirm, name='apply_confirm'),
    url(r'^faq/$', lots_client.views.faq, name='faq'),
    url(r'^about/$', lots_client.views.about, name='about'),
    #url(r'^lots-admin/$', 'lots_admin.views.lots_admin', name='lots_admin'),
    #url(r'^lots-admin-map/$', 'lots_admin.views.lots_admin_map', name='lots_admin_map'),
    #url(r'^csv-dump/$', lots_admin.views.csv, name='csv_dump'),
    url(r'^lots-login/$', lots_admin.views.lots_login, name='lots_login'),
    url(r'^logout/$', lots_admin.views.lots_logout, name='logout'),

    url(r'^django-admin/', admin.site.urls),
]

lots_admin/models.py
from django.db import models
import time

class Address(models.Model):
    street = models.CharField(max_length=255)
    city = models.CharField(max_length=20, default='Cleveland')
    state = models.CharField(max_length=20, default='OH')
    zip_code = models.CharField(max_length=10, null=True)

    def __unicode__(self):
        return '%s %s, %s %s' % \
            (self.street, self.city, self.state, self.zip_code)

def upload_name(instance, filename):
    now = int(time.time())
    print (instance.first_name, instance.last_name)
    return 'plans/%s-%s-%s_%s' % \
        (instance.first_name, instance.last_name, now, filename)

class Application(models.Model):
    first_name = models.CharField(max_length=255, null=True)
    last_name = models.CharField(max_length=255, null=True)
    # organization = models.CharField(max_length=255, null=True)
    # owned_ppn = models.CharField(max_length=14)


    owned_address = models.ForeignKey(Address, related_name='owned_address')
    owned_live = models.CharField(max_length=40)
    owned_properties = models.CharField(max_length=40)
    owned_properties_info = models.CharField(max_length=255, null=True)

    lot_1_use = models.CharField(max_length=5)
    lot_1_improvements = models.CharField(max_length=5)
    lot_1_descr = models.CharField(max_length=255, null=True)

    plan_image = models.FileField(upload_to=upload_name)
    fencing_descr = models.CharField(max_length=255, null=True)
    fencing_cost = models.CharField(max_length=255, null=True)

    landscaping_descr = models.CharField(max_length=255, null=True)
    landscaping_cost = models.CharField(max_length=255, null=True)

    apron_descr = models.CharField(max_length=255, null=True)
    apron_cost = models.CharField(max_length=255, null=True)

    other_descr = models.CharField(max_length=255, null=True)
    other_cost = models.CharField(max_length=255, null=True)

    contact_address = models.ForeignKey(Address, related_name='contact_address')
    phone = models.CharField(max_length=15)
    phone_2 = models.CharField(max_length=15)
    email = models.CharField(max_length=255, null=True)
    how_heard = models.CharField(max_length=255, null=True)
    tracking_id = models.CharField(max_length=40)
    status = models.CharField(max_length=50, null=True)
    received_date = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        if self.first_name and self.last_name:
            return '%s %s' % (self.first_name, self.last_name)
        # elif self.organization:
        #     return self.organization


class Lot(models.Model):
    ppn = models.CharField(max_length=14, primary_key=True)
    address = models.ForeignKey(Address)
    application = models.ManyToManyField(Application)

    # planned_use = models.CharField(max_length=20, default=None, null=True)

    def __unicode__(self):
        return self.ppn

templates/about.html
{% extends "base.html" %}
{% block title %} | About {% endblock %}
{% block content %}
  <div class='col-md-8'>
    <h2>About</h2>

    <p>The <strong>Cleveland Lots</strong> website is brought to you by <a href='http://opencleveland.org'>Open Cleveland</a>, a Code for America brigade, in conjunction with the <a href='http://portal.cleveland-oh.gov/CityofCleveland/Home/Government/CityAgencies/CommunityDevelopment/LandBank'>City of Cleveland Land Bank</a> and supported by <a href='http://www.npi-cle.org/'>Cleveland Neighborhood Progress</a>. The program aims to:</p>
    <ul>
      <li>Give local residents greater access to vacant land in their neighborhood</li>
      <li>Dispose of some of the City-owned land in these neighborhoods efficiently, which returns the land to the tax rolls</li>
      <li>Increase safety, build community, and raise home values by creating more neighborhood-level investment</li>
    </ul>

    <h3>Built with open data</h3>
    <p>This site was built using data from the <a href='http://neocando.case.edu/nst/'>NST web application</a>, provided by the <a href='http://povertycenter.case.edu/'>Center on Urban Poverty and Community Development</a> at Case Western Reserve University.
      
    <p>We prepared some extracts of the above sources for this project. You can download those here:</p>

    <ul>
        <li>Available lots (<a href="https://opencleveland.cartodb.com/tables/joined/public/table">CartoDB</a>, downloadable as CSV, SHP, GEOJSON</li>
        <li>Parcel boundaries (<a href="https://brigades.opendatanetwork.com/NEIGHBORHOODS/Cleveland-Parcel-Boundaries/auw9-csgs"> Socrata</a>, downloadable as CSV, JSON, SHP, KML) </li>
    </ul>

    <h3>Open source code</h3>
    <p>All the code for this site is open source and <a href='https://github.com/opencleveland/large-lots'>available on Github</a>. This project is forked from <a href='https://github.com/datamade/large-lots'>DataMade</a>, who built the original Large Lots site for <a href='https://largelots.org'>Chicago</a>. We used the following open source tools:</p>

    <ul>

      <li><a href='https://www.djangoproject.com'>Django</a> - web framework</li>
      <li><a href='http://getbootstrap.com/'>Bootstrap</a> - Responsive HTML, CSS and Javascript framework</li>
      <li><a href='http://leafletjs.com/'>Leaflet</a> - javascript library interactive maps</li>
      <li><a href='http://cartodb.com'>CartoDB</a> - platform for rendering interactive map tiles</li>
      <li><a href='https://csvkit.readthedocs.org/en/0.9.1/'>csvkit</a> - command line utility tool for working with CSV files</li>
      <li><a href='https://github.com/asual/jquery-address'>jQuery Address</a> - javascript library creating RESTful URLs</li>
    </ul>

    <h3>Press</h3>

    <p> Hopefully we'll get some soon!
  </div>
{% endblock %}

templates/admin-map.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %} | Lots applied for {% endblock %}
{% block extra_css %}
    <style id="egp-styles">
      #egp_parcels {
        polygon-fill: #41ab5d;
        polygon-opacity: 0.7;
        line-color: #006d2c;
        line-width: 0.5;
        line-opacity: 1;
      }
    </style>
    <style id="egp-styles-applied">
        #egp_parcels {
          polygon-fill: #A1285D;
          polygon-opacity: 0.7;
          line-color: #680D35;
          line-width: 0.5;
          line-opacity: 1;
        }
    </style>
{% endblock %}
{% block content %}
<p><a href='/lots-admin/'>&laquo; back to the list</a></p>
<h2><span id='ppn_count'></span> Lots applied for </h2>

<p>
    <span class='label label-available'>Available</span>
    <span class='label label-applied'>Applied</span>
</p>

<div id='map-admin'></div>

{% endblock %}
{% block extra_js %}
    <script src="//libs.cartocdn.com/cartodb.js/v3/cartodb.js"></script>

    <script src="{% static 'js/leaflet.label.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/largelots_admin.js' %}"></script>
    <script>

      var applied_ppns = "{{applied_ppns|safe}}";
      var num_ppns = $.unique(applied_ppns.split(",")).length;
      var num_parcels = 8000.0 // estimate!
      var applied_percent = (100 * num_ppns / num_parcels).toFixed(1);

      $('#ppn_count').html(num_ppns + " out of 8000 (" + applied_percent + "%)")
      $(function() {
        LargeLotsAdmin.initialize();
      });
    </script>
{% endblock %}

templates/admin.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %} | Application list {% endblock %}
{% block content %}
<h2>Applications Received</h2>
<p><a href="/lots-admin-map/"><i class='fa fa-map-marker'></i> Map view</a> &nbsp;&nbsp;&nbsp; <a href="{% url 'csv_dump' %}"><i class='fa fa-file-excel-o'></i> Export as CSV</a></p>
<table id="received" class="table table-striped">
    <thead>
        <th>ID</th>
        <th>Date received</th>
        <th>Name/Organization</th>
        <th>Applied lot</th>
        <th>Contact info</th>
        <th>Owned property</th>
        <th></th>
    </thead>
    <tbody>
    {% for application in applications %}
        <tr>
            <td>{{application.id}}</td>
            <td>{{application.received_date|date:'Y-m-d g:i a'}}</td>
            <td>
                {{application.first_name}} {{application.last_name}}
                <!-- {% if application.organization %}
                <br />
                  {{application.organization}}
                {% endif %} -->
            </td>
            <td>
                {% for lot in application.lot_set.all %}
                    <p>
                        {{lot.address.street}}<br />
                        {{lot.ppn}}
                    </p>
                {% endfor %}
            </td>
            <td>{{application.contact_address.street}} <br /> {{application.phone}} <br /> {{application.email}}</td>
            <td>
                {{application.owned_address.street}}<br />
                <a href="{{application.plan_image.url}}" target="_blank">Download plan</a>
            </td>
            <td><a href="{% url 'apply_confirm' application.tracking_id %}" target="_blank">Detail page</a></td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}
{% block extra_js %}
    <script src="{% static 'js/jquery.tablesorter.min.js' %}" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            $('#received').tablesorter( {sortList: [[0,1]] } );
        })
    </script>
{% endblock %}

templates/apply_confirm.html
{% extends "base.html" %}
{% load lots_filters %}
{% block title %} | Confirmation {% endblock %}
{% block content %}
<div class="col-sm-8 col-sm-offset-2">
    <div class="row">
        <div class="col-sm-12">
            <p>
                <a class='btn btn-default' id='print-page' href="#">
                    <i class='fa fa-print'></i>Print this page for your records
                </a>
            </p>
            <h1>Thanks for applying, {{app.first_name}}!</h1>
            {% if app.email %}
            <p>You should receive confirmation email shortly.</p>
            {% endif %}

 <div class="row">
        <div class="col-sm-12">
            <h3>Application information: </h3>
            <table class="table table-bordered table-condensed">
                <tbody>
                    <tr>
                        <td>Application ID</td>
                        <td>
                            {{app.tracking_id}}
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
 </div>

            <h3>Lot information:</h3>
            {% if lots|length > 1 %}
        </div>
        {% for lot in lots %}
            <div class="col-sm-6">
<!--
                <img class="img-responsive img-thumbnail" src="http://cookviewer1.cookcountyil.gov/Jsviewer/image_viewer/requestImg.aspx?{{lot.pin|remove_str:'-'}}=" />
-->
                <table class="table table-bordered table-condensed">
                    <tbody>
                        <tr>
                            <td>Address</td>
                            <td>{{lot.address.street}}</td>
                        </tr>
                        <tr>
                            <td>PPN</td>
                            <td>
                                {{lot.ppn}}  
			    </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        {% endfor %}
        {% else %}
        </div>
        {% for lot in lots %}
        <div class="col-sm-12">
<!--
            <img class="img-responsive img-thumbnail" src="http://cookviewer1.cookcountyil.gov/Jsviewer/image_viewer/requestImg.aspx?{{lot.pin|remove_str:'-'}}=" />
-->
            <table class="table table-bordered table-condensed">
                <tbody>
                    <tr>
                        <td>Address</td>
                        <td>{{lot.address.street}}</td>
                    </tr>
                    <tr>
		      <td>PPN</td>
                            <td>
                            {{lot.ppn}}
                            </td>
                    </tr>
                </tbody>
            </table>
        </div>
        {% endfor %}
        {% endif %}
    </div>
    <div class="row">
        <div class="col-sm-12">
            <h3>Ownership information: </h3>
            <table class="table table-bordered table-condensed">
                <tbody>
                    <tr>
                        <td>Address</td>
                        <td>
                            {{app.owned_address.street}}
                            {{app.owned_address.city}},
                            {{app.owned_address.state}}
                        </td>
                    </tr>
                    <tr>
                        <td>Plan image</td>
                        <td><a href="{{app.plan_image.url}}" target="_blank">Download</a></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <h3>Contact information:</h3>
            <table class="table table-bordered table-condensed">
                <tbody>
                    <tr>
                        <td>Name</td>
                        <td>{{app.first_name}} {{app.last_name}}</td>
                    </tr>
                    <tr>
                        <td>Address (blank if same as owned property)</td>
			<td>
                            {{app.contact_address.street}}
                            {{app.contact_address.city}},
                            {{app.contact_address.state}}
                            {{app.contact_address.zip_code}}
                        </td>
                    </tr>
                    <tr>
                        <td>Phone</td>
                        <td>{{app.phone}}</td>
                    </tr>
                    {% if app.phone_2 %}
                        <tr>
                            <td>Secondary phone</td>
                            <td>{{app.phone_2}}</td>
                        </tr>
                    {% endif %}
                    {% if app.email %}
                        <tr>
                            <td>Email</td>
                            <td>{{app.email}}</td>
                        </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <p><strong>If you have any questions, please contact:</strong></p>
            <p>
              City of Cleveland Land Bank<br />
              Phone: (216) 664-4126<br />
              Email: <a href='mailto:CD-DND@city.cleveland.oh.us'>CD-DND@city.cleveland.oh.us</a>
            </p>
        </div>
    </div>
</div>
{% endblock %}
{% block extra_js %}
    <script type="text/javascript">
      $("#print-page").on("click", function(){ window.print(); });
    </script>
{% endblock %}

templates/apply_html_email.html
{% load lots_filters %}
<div class="row">
    <h1>Thanks for applying, {{app.first_name}}!</h1>
    <p><a href="//{{host}}/apply-confirm/{{app.tracking_id}}/">View this confirmation on ClevelandLots.org</a></p>

<div class="row">
    <h3>Application information:</h3>
    <table class="table table-bordered table-condensed">
        <tbody>
            <tr>
                <td>Application ID:</td>
                <td>
                    {{app.tracking_id}}
                </td>
            </tr>
        </tbody>
    </table>
</div>

    <h3>Lot information:</h3>
    {% for lot in lots %}
        <div>
            <table>
                <tbody>
                    <tr>
                        <td>Address:</td>
                        <td>{{lot.address.street}}</td>
                    </tr>
                    <tr>
                        <td>PPN:</td>
                        <td>{{lot.ppn}}</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <br />
        <br />
    {% endfor %}
</div>
<div class="row">
    <h3>Ownership information:</h3>
    <table class="table table-bordered table-condensed">
        <tbody>
            <tr>
                <td>Address:</td>
                <td>
                    {{app.owned_address.street}}
                    {{app.owned_address.city}},
                    {{app.owned_address.state}}
                </td>
            </tr>
        </tbody>
    </table>
</div>
<div class="row">
    <h3>Contact information:</h3>
    <table>
        <tbody>
            <tr>
                <td>Name:</td>
                <td>{{app.first_name}} {{app.last_name}}</td>
            </tr>
            <!-- <tr>
                <td>Organization</td>
                <td>{{app.organization}}</td>
            </tr> -->
            <tr>
                <td>Address (blank if same as owned property):</td>
                <td>
                    {{app.contact_address.street}}
                    {{app.contact_address.city}},
                    {{app.contact_address.state}}
                    {{app.contact_address.zip_code}}
                </td>
            </tr>
            <tr>
                <td>Phone:</td>
                <td>{{app.phone}}</td>
            </tr>
            <tr>
                <td>Email:</td>
                <td>{{app.email}}</td>
            </tr>
        </tbody>
    </table>
</div>
<div>
    <p><strong>If you have any questions, please contact:</strong></p>
    <p>
      City of Cleveland Land Bank<br />
      Phone: (216) 664-4126<br />
      Email: CD-DND@city.cleveland.oh.us
    </p>
</div>

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="/static/images/favicon.ico">

    <title>Large Lots {% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="{% static 'js/html5shiv.js' %}"></script>
      <script src="{% static 'js/respond.min.js' %}"></script>
    <![endif]-->

    <!-- <link href="//cdn.leafletjs.com/leaflet-0.5/leaflet.css" media="screen" rel="stylesheet" type="text/css" /> -->
    <!-- <link href="css/leaflet.label.css" media="all" rel="stylesheet" type="text/css" /> -->
    <link rel="stylesheet" href="//libs.cartocdn.com/cartodb.js/v3/themes/css/cartodb.css" />
    {% block extra_css %}{% endblock %}
  </head>

  <body>
    <div class="navbar navbar-inverse" role="navigation">
      <div class="container">
        {% block nav %}
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a id='logo' href="/"><img src='{% static 'images/large_lots.png' %}' alt='Large Lots' /></a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav pull-right">
            <li {% if request.path == '/' %}class='active' {% endif %}><a href="{% url 'home' %}">Home</a></li>
            <li {% if request.path == '/apply/' %}class='active' {% endif %}><a href="{% url 'apply' %}">Apply</a></li>
            <li {% if request.path == '/faq/' %}class='active' {% endif %}><a href="{% url 'faq' %}">FAQ</a></li>
            <li {% if request.path == '/about/' %}class='active' {% endif %}><a href="{% url 'about' %}">About</a></li>
            {% if request.user.is_authenticated %}<li><a href="{% url 'logout' %}">Logout</a></li>{% endif %}
          </ul>
        </div><!--/.nav-collapse -->
        {% endblock %}
      </div>
    </div>
    <div class="container" id="main-content">
      {% block content %}{% endblock %}

      <div class='clearfix'></div>
      <div class="footer">
        <p class='pull-right'>By <a href='http://www.opencleveland.org/'>Open Cleveland</a>, Based On Large Lots Chicago from <a href="http://www.lisc-chicago.org/">LISC Chicago</a> and <a href='http://datamade.us'>DataMade</a><br />
      </div>
    </div> <!-- /container -->
    {% block modals %}{% endblock %}
    <script src="{% static 'js/jquery-1.10.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/analytics_lib.js' %}"></script>
    {% block extra_js %}{% endblock %}

  </body>
</html>

templates/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
      <div class='col-md-12'>

        <br />
        <p class='lead'>The City of Cleveland is selling vacant residential lots for side yard expansion for <strong>$200</strong>. Find out if you qualify.</p>

        <div class='row'>
          <div class='col-md-8 col-md-offset-2'>
            <div class='well'>



               <p><a href='{% url "apply" %}'>Search and apply for a lot today!</a>                </p>

                <div class='row'>
                  <div class='col-md-10 col-md-offset-1'>
                    <p><a href='{% url "apply" %}'><img src='{% static "images/cleveland_map.png" %}' class='img-responsive img-thumbnail' alt='Cleveland large lots locations' /></a></p>
                  </div>
                </div>

                <p class='text-center'><a href='{% url "apply" %}' class="btn btn-success btn-lg">Apply for a lot</a></p>
            </div>
          </div>



        <div class='row'>
          <div class='col-md-8'>
            <h3>About</h3>
            <p><strong>Cleveland Lots</strong> is an online application for side yard expansion in Cleveland and was developed by Open Cleveland with the City of Cleveland Land Bank.</p>
            <!-- <p>The <strong>Large Lot Program</strong> is a housing land use approach that was developed as part of the <a href='http://www.cityofchicago.org/city/en/depts/dcd/supp_info/green-healthy-neighborhoods.html'>Green Healthy Neighborhoods</a> public planning process. This website was built to make the process of purchasing City-owned land through this program easier for residents. <a href='/about'>Read more &raquo;</a> -->
          </div>
        </div>
      </div>

{% endblock %}

templates/lots_login.html
{% extends "base.html" %}
{% block title %} | Login {% endblock %}
{% block content %}
    <div class="row">
        <div class="well col-md-6 col-md-offset-3">
            <form role="form" method="POST">
                {% csrf_token %}
                {{ form.non_field_errors }}
                {% if form.username.errors %}
                    <div class="form-group has-error has-feedback">
                {% else %}
                    <div class="form-group">
                {% endif %}
                    <label for="id_username">Username:</label>
                    <input type="text" class="form-control" id="id_username" name="username" placeholder="Enter username">
                    {% if form.username.errors %}
                        <span class="glyphicon glyphicon-remove form-control-feedback"></span>
                        <span class="help-block">{{form.username.errors}}</span>
                    {% endif %}
                </div>
                {% if form.password.errors %}
                    <div class="form-group has-error has-feedback">
                {% else %}
                    <div class="form-group">
                {% endif %}
                    <label for="id_password">Password</label>
                    <input type="password" class="form-control" id="id_password" name="password" placeholder="Password">
                    {% if form.password.errors %}
                        <span class="glyphicon glyphicon-remove form-control-feedback"></span>
                        <span class="help-block">{{form.password.errors}}</span>
                    {% endif %}
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/status.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %} | Application status {% endblock %}
{% block extra_css %}
    <style id="englewood-styles">
      #full_area_lots {
        polygon-fill: #6ac682;
        polygon-opacity: 0.7;
        line-color: #389250;
        line-width: 0.5;
        line-opacity: 1;
      }
      #full_area_lots[status=2]{
        polygon-fill: #A1285D;
        line-color: #680D35;
      }
    </style>
{% endblock %}
{% block content %}
      <div class='col-md-12'>

        <div class='row'>
          <div class='col-md-12'>
            <h1>Greater Englewood Area <small class='closed'>Closed</small></h1>
            <div class='row'>
              <div class='col-md-9'>
                <p>The Englewood pilot ended on <strong>April 21st, 2014</strong> and <strong>414 applications</strong> for lots were received.</p>

                <p>On August 21st, 2014, the sale of <strong>317 properties</strong> was approved by the <a href='http://www.cityofchicago.org/city/en/depts/dcd/supp_info/chicago_plan_commission.html'>Chicago Plan Commission</a>. Closings are anticipated for late fall,  pending City Council approval.</p>

                <p>Browse the map or enter your address below to see what lots have been <strong class='closed'>applied for and approved</strong> by the Chicago Plan Commission.</p>
              </div>
            </div>

            <p>
              <form class='form-inline hidden-print' id='lot-form'>
                <div class="form-group">
                  <input class='form-control input-lg' id='search_address' placeholder='Enter your address' type='text' />
                  <input class='btn btn-primary btn-lg' id='search' type='button' value='Search' />
                </div>
                <div class="form-group">
                    <input id="available" class="toggle-parcels checkbox" type="checkbox" />

                    <label for='available'><span class="label label-available">Not applied for</span></label>

                    <input id="applied" class="toggle-parcels checkbox" type="checkbox" checked=true />
                    <label for='applied'><span class="label label-applied">Application approved</span></label>
                </div>
              </form>
            </p>
          </div>

          <div class='col-md-8'>
            <div id='map'></div>
          </div>
          <div class='col-md-4'>
            <div class='well' id='lot-info'>
              <p>To get started:</p>

              <ol>
                <li>Enter your address to view available lots near you</li>
                <li>Click on a lot on the map for details</li>
              </ol>
            </div>
          </div>
        </div>
      </div>
{% endblock %}
{% block extra_js %}
    <script type="infowindow/html" id="infowindow_template">
    <div class="cartodb-popup">
      <a href="#close" class="cartodb-popup-close-button close">x</a>
      // <div class="cartodb-popup-content-wrapper">
      //   <div class="cartodb-popup-content">
      //     <h4>{{content.data.street_number}} {{content.data.dir}} {{content.data.street_name}} {{content.data.type}}</h4>
      //       <p>PIN: {{content.data.pin14}}<br />
      //       Zoned: {{content.data.zoning_classification}}<br />
      //       Sq Ft: {{content.data.sq_ft}}<br />
      //       Alderman: (Ward {{content.data.ward}})</p>
      //   </div>
      // </div>
      // <div class="cartodb-popup-tip-container"></div>
    </div>
    </script>
    <script src="{% static 'js/jquery.address.js' %}"></script>
    <script src="//libs.cartocdn.com/cartodb.js/v3/cartodb.js"></script>

    <!--<script src="js/leaflet.js" type="text/javascript"></script> -->
    <script src="{% static 'js/leaflet.label.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/largelots_pilot1.js' %}"></script>

    <script>
      $(function() {
        LargeLots.initialize();
      });

      $("#search").on("click", LargeLots.addressSearch);
      $("#search_address").on("keydown", function(e){
        if(e.keyCode == 13){
          LargeLots.addressSearch(e);
        }
      });

      $("#print-page").on("click", function(){ window.print(); });
    </script>
{% endblock %}